services:
  user-db:
    image: postgres:17
    container_name: user-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${USERDB_USERNAME}
      POSTGRES_PASSWORD: ${USERDB_PASSWORD}
      POSTGRES_DB: ${USERDB_DATABASE}
    ports:
      - 5433:5432
    volumes:
      - userdb_data:/var/lib/postgresql/data

  trip-db:
    image: postgres:17
    container_name: trip-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${TRIPDB_USERNAME}
      POSTGRES_PASSWORD: ${TRIPDB_PASSWORD}
      POSTGRES_DB: ${TRIPDB_DATABASE}
    ports:
      - 5434:5432
    volumes:
      - tripdb_data:/var/lib/postgresql/data

  driver-db:
    image: postgres:17
    container_name: driver-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DRIVERDB_USERNAME}
      POSTGRES_PASSWORD: ${DRIVERDB_PASSWORD}
      POSTGRES_DB: ${DRIVERDB_DATABASE}
    ports:
      - 5435:5432
    volumes:
      - driverdb_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: driver-redis
    environment:
      REDIS_HOST: redis
    ports:
      - 6379:6379

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

volumes:
  userdb_data:
  tripdb_data:
  driverdb_data:
