services: 
  user-db: 
    image: postgres:17
    container_name: user-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${USERDB_USERNAME}
      POSTGRES_PASSWORD: ${USERDB_PASSWORD}
      POSTGRES_DB: ${USERDB_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - userdb_data:/var/lib/postgresql/data

  trip-db: 
    image: postgres:17
    container_name: trip-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${TRIPDB_USERNAME}
      POSTGRES_PASSWORD: ${TRIPDB_PASSWORD}
      POSTGRES_DB: ${TRIPDB_DATABASE}
    ports: 
      - 5433:5432
    volumes:
      - tripdb_data:/var/lib/postgresql/data

  driver-db: 
    image: postgres:17
    container_name: driver-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DRIVERDB_USERNAME}
      POSTGRES_PASSWORD: ${DRIVERDB_PASSWORD}
      POSTGRES_DB: ${DRIVERDB_DATABASE}
    ports: 
      - 5434:5432
    volumes:
      - driverdb_data:/var/lib/postgresql/data

  redis: 
    image: redis:7-alpine
    container_name: driver-redis
    environment:
      REDIS_HOST: redis
    ports:
      - 6379:6379

volumes:
  userdb_data:
  tripdb_data:
  driverdb_data: